"""Synthetic AD-flavoured cohort generator and GSE121212 loader.

The synthetic generator is the workhorse for tutorials, tests, and the
default Streamlit demo. It builds a cohort whose ground truth indirect
effect is *known by construction*, so users can sanity-check their
estimates against ``ground_truth_*`` attributes on the returned object.

`load_gse121212` is an opt-in real-data loader that uses GEOparse to
download GSE121212 (Tsoi et al., 2019: "Atopic Dermatitis Is an IL-13-
Dominant Disease..."), aggregates probe expression to gene level, and
returns a tidy DataFrame ready for `mediation_analysis`.
"""
from __future__ import annotations

from dataclasses import dataclass, field

import numpy as np
import pandas as pd


@dataclass
class CohortBundle:
    """Container returned by `simulate_ad_cohort`."""

    df: pd.DataFrame
    transcript_cols: list[str] = field(default_factory=list)
    metab_cols: list[str] = field(default_factory=list)
    microbiome_cols: list[str] = field(default_factory=list)
    confounder_cols: list[str] = field(default_factory=list)
    pathway_map: dict[str, list[str]] = field(default_factory=dict)
    ground_truth_total: float | None = None
    ground_truth_direct: float | None = None
    ground_truth_indirect: float | None = None
    ground_truth_per_block: dict[str, float] = field(default_factory=dict)


def simulate_ad_cohort(
    n: int = 400,
    p_transcript: int = 200,
    p_metab: int = 50,
    p_microbiome: int = 30,
    n_active_transcript: int = 6,
    n_active_metab: int = 3,
    n_active_microbiome: int = 2,
    n_pathways: int = 8,
    effect_strength: float = 0.6,
    noise: float = 1.0,
    seed: int | None = 0,
) -> CohortBundle:
    """Simulate a multi-omic AD cohort with a known mediation structure.

    Variables generated
    -------------------
    Confounders: ``age`` (years, ~N(35, 12)), ``sex`` (binary), ``BMI``
        (~N(25, 4)), ``smoking`` (binary).
    Exposure: ``filaggrin_LoF`` (binary, prevalence 0.12) representing a
        filaggrin loss-of-function variant — the canonical AD risk allele.
    Mediators:
      * Transcriptome: ``T0001..T{p_transcript}``. The first
        ``n_active_transcript`` are the *active* mediators.
      * Metabolome: ``MET01..MET{p_metab}``; first ``n_active_metab`` active.
      * Microbiome: ``MIC01..MIC{p_microbiome}``; first
        ``n_active_microbiome`` active.
    Outcome: ``SCORAD`` (0..100-ish severity score; here we leave it
        Gaussian-scaled around a clinically plausible mean).

    Pathways are generated by partitioning the transcript columns into
    contiguous chunks; the first pathway is enriched for active mediators.
    """
    rng = np.random.default_rng(seed)

    # Confounders
    age = rng.normal(35, 12, n).clip(5, 90)
    sex = rng.integers(0, 2, n)
    bmi = rng.normal(25, 4, n).clip(15, 50)
    smoking = (rng.uniform(size=n) < 0.18).astype(int)

    # Exposure (FLG LoF), with a slight age dependency to give confounding teeth
    p_flg = 0.10 + 0.001 * (age - 35)
    p_flg = np.clip(p_flg, 0.02, 0.4)
    flg = (rng.uniform(size=n) < p_flg).astype(int)

    # Mediator blocks
    def make_block(p: int, n_active: int, prefix: str, alpha_scale: float) -> tuple[pd.DataFrame, np.ndarray]:
        cols = [f"{prefix}{i+1:04d}" for i in range(p)]
        # Background expression with mild age/sex effects
        base = rng.normal(0, 1, (n, p))
        # Active mediators receive an X effect; signs are deterministic (all positive)
        # so that the ground truth indirect effect is stable and recoverable.
        alphas = np.zeros(p)
        alphas[:n_active] = np.abs(rng.normal(alpha_scale, 0.15, n_active))
        block = base + np.outer(flg, alphas)
        # Add small confounder leak so adjusting matters
        block[:, : min(p, 5)] += 0.05 * (age[:, None] - 35) / 12
        return pd.DataFrame(block, columns=cols), alphas

    tx_df, tx_alpha = make_block(p_transcript, n_active_transcript, "T", effect_strength)
    met_df, met_alpha = make_block(p_metab, n_active_metab, "MET", effect_strength * 0.8)
    mic_df, mic_alpha = make_block(p_microbiome, n_active_microbiome, "MIC", effect_strength * 0.6)

    # Outcome model: SCORAD = b0 + b_X*X + b_M*M_active + confounders + noise
    bx = 1.5  # direct effect
    beta_tx = np.zeros(p_transcript)
    beta_tx[:n_active_transcript] = np.abs(rng.normal(1.0, 0.2, n_active_transcript))
    beta_met = np.zeros(p_metab)
    beta_met[:n_active_metab] = np.abs(rng.normal(0.9, 0.2, n_active_metab))
    beta_mic = np.zeros(p_microbiome)
    beta_mic[:n_active_microbiome] = np.abs(rng.normal(0.7, 0.2, n_active_microbiome))

    eps = rng.normal(0, noise, n)
    scorad = (
        20.0
        + bx * flg
        + tx_df.values @ beta_tx
        + met_df.values @ beta_met
        + mic_df.values @ beta_mic
        + 0.05 * (age - 35)
        + 1.2 * sex
        + 0.1 * (bmi - 25)
        + eps
    )

    df = pd.DataFrame(
        {
            "age": age,
            "sex": sex,
            "BMI": bmi,
            "smoking": smoking,
            "filaggrin_LoF": flg,
            "SCORAD": scorad,
        }
    )
    df = pd.concat([df, tx_df, met_df, mic_df], axis=1)

    # Ground truth indirect contributions: sum_j alpha_j * beta_j
    nie_tx = float(np.sum(tx_alpha * beta_tx))
    nie_met = float(np.sum(met_alpha * beta_met))
    nie_mic = float(np.sum(mic_alpha * beta_mic))
    nie_total = nie_tx + nie_met + nie_mic

    # Pathway map: split transcript columns into contiguous chunks.
    pathway_map: dict[str, list[str]] = {}
    chunk = max(1, p_transcript // n_pathways)
    for k in range(n_pathways):
        start = k * chunk
        end = (k + 1) * chunk if k < n_pathways - 1 else p_transcript
        cols = list(tx_df.columns[start:end])
        # Make pathway 1 a "Th2 / barrier" pathway containing all active mediators
        if k == 0:
            cols = list(tx_df.columns[:max(chunk, n_active_transcript + 2)])
        pathway_map[f"PATHWAY_{k+1:02d}"] = cols

    return CohortBundle(
        df=df,
        transcript_cols=list(tx_df.columns),
        metab_cols=list(met_df.columns),
        microbiome_cols=list(mic_df.columns),
        confounder_cols=["age", "sex", "BMI", "smoking"],
        pathway_map=pathway_map,
        ground_truth_total=bx + nie_total,
        ground_truth_direct=bx,
        ground_truth_indirect=nie_total,
        ground_truth_per_block={
            "transcriptome": nie_tx,
            "metabolome": nie_met,
            "microbiome": nie_mic,
        },
    )


# ---------------------------------------------------------------------------
# GSE121212 loader (optional dependency: GEOparse)
# ---------------------------------------------------------------------------

def load_gse121212(
    cache_dir: str | None = None,
    top_var_genes: int = 500,
    use_cache: bool = True,
) -> CohortBundle:
    """Load GSE121212 as a `CohortBundle` ready for mediation analysis.

    Exposure : ``lesional`` (1 = lesional AD skin, 0 = non-lesional / healthy)
    Outcome  : ``severity_score`` — a synthetic-but-data-driven score
               constructed as the first PC of a hand-picked Th2/Th17 panel
               (because GSE121212 ships with categorical labels rather than
               continuous SCORAD); useful as a *demonstration* outcome only.
    Mediators: top-variance ``top_var_genes`` genes after expression
               aggregation across probes.

    Notes
    -----
    Requires ``pip install skinflame[geo]``. The first call downloads the
    GEO matrix file (~50 MB) and caches it.
    """
    try:
        import GEOparse  # noqa: F401
    except ImportError as e:  # pragma: no cover
        raise ImportError(
            "GEOparse is required for the GSE121212 loader. "
            "Install with: pip install skinflame[geo]"
        ) from e

    import os
    from pathlib import Path

    import GEOparse

    cache = Path(cache_dir or os.path.expanduser("~/.skinflame_cache"))
    cache.mkdir(parents=True, exist_ok=True)

    gse = GEOparse.get_GEO(geo="GSE121212", destdir=str(cache), silent=True)

    # Build a (samples x genes) matrix.
    # GSE121212 uses Affymetrix Clariom D human; gene symbols are in the
    # platform annotation table.
    # We aggregate by max-mean per gene symbol.
    sample_ids = list(gse.gsms.keys())
    expr_columns = []
    sample_meta_rows = []
    for sid in sample_ids:
        gsm = gse.gsms[sid]
        chars = " | ".join(gsm.metadata.get("characteristics_ch1", [])).lower()
        title = " ".join(gsm.metadata.get("title", [])).lower()
        # Heuristic labelling; GSE121212 titles include 'lesional', 'nonlesional', 'normal'.
        if "non" in title and "lesional" in title:
            lesional = 0
            condition = "nonlesional_AD"
        elif "lesional" in title and "ad" in title:
            lesional = 1
            condition = "lesional_AD"
        elif "normal" in title or "control" in title or "healthy" in chars:
            lesional = 0
            condition = "control"
        else:
            lesional = -1
            condition = "unknown"
        sample_meta_rows.append({"sample_id": sid, "lesional": lesional, "condition": condition})
        expr = gsm.table.set_index("ID_REF")["VALUE"].astype(float)
        expr.name = sid
        expr_columns.append(expr)

    expr_df = pd.concat(expr_columns, axis=1)
    # Map probe -> gene symbol via the GPL annotation
    gpl = next(iter(gse.gpls.values()))
    ann = gpl.table.set_index("ID")
    gene_col = None
    for cand in ("Gene Symbol", "gene_assignment", "GENE_SYMBOL", "Symbol"):
        if cand in ann.columns:
            gene_col = cand
            break
    if gene_col is None:
        # As a fallback, keep probe IDs as "genes"
        gene_symbols = ann.index.astype(str)
    else:
        gene_symbols = ann[gene_col].astype(str).str.split(" /// ").str[0]
    gene_symbols = gene_symbols.reindex(expr_df.index)

    expr_df["__gene__"] = gene_symbols.values
    expr_df = expr_df.dropna(subset=["__gene__"])
    expr_df = expr_df[expr_df["__gene__"] != ""]
    gene_expr = expr_df.groupby("__gene__").mean()  # samples are columns
    # samples x genes
    gene_expr = gene_expr.T

    # Top-variance gene selection
    variances = gene_expr.var(axis=0).sort_values(ascending=False)
    top_genes = variances.index[:top_var_genes].tolist()
    gene_expr = gene_expr[top_genes]

    meta = pd.DataFrame(sample_meta_rows).set_index("sample_id")
    df = meta.join(gene_expr).dropna()
    df = df[df["lesional"] >= 0].reset_index(drop=True)

    # Pseudo-outcome: first PC of canonical AD/Th2 markers if any are present.
    canonical = [g for g in ["IL13", "IL4R", "CCL18", "CCL17", "S100A7", "S100A8", "S100A9", "IL17A", "IL22"] if g in gene_expr.columns]
    from sklearn.decomposition import PCA
    if canonical:
        sev = PCA(n_components=1).fit_transform(df[canonical].to_numpy())[:, 0]
    else:
        sev = PCA(n_components=1).fit_transform(df[gene_expr.columns[:20]].to_numpy())[:, 0]
    # Sign-align so lesional has higher score on average
    if df.loc[df["lesional"] == 1, :].index.size:
        sign = 1.0 if sev[df["lesional"].to_numpy() == 1].mean() > sev[df["lesional"].to_numpy() == 0].mean() else -1.0
        sev = sign * sev
    df["severity_score"] = sev

    return CohortBundle(
        df=df.drop(columns=["condition"]),
        transcript_cols=list(gene_expr.columns),
        metab_cols=[],
        microbiome_cols=[],
        confounder_cols=[],
        pathway_map={},
    )
